config/routes.rb
Rails.application.routes.draw do
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

namespace :admin do
    namespace :api, defaults: {format: :json} do
      namespace :v1 do
        resources :recruiters
        resources :jobs
        resources :pipeline_steps
        resources :candidates
        resources :jobs_candidates
        resources :jobs_candidates_pipelines, only: [:update]
      end
    end

    resources :recruiters
    resources :jobs
    resources :pipeline_steps
    resources :candidates
    resources :jobs_candidates
    resources :jobs_candidates_pipelines, only: [:update]
end

# Defines the root path route ("/")
# root "articles#index"
get 'postulation/:token', to: 'candidates_experiences#index'

end

app/models/jobs_candidate.rb
class JobsCandidate < ApplicationRecord
  enum status: [:inactive, :active]
  
  #--------------------------------------------- RELATIONSHIPS
  belongs_to :job
  belongs_to :candidate
  has_many :jobs_candidates_pipeline

  #--------------------------------------------- CALLBACK
  after_save :add_pipelines_to_jobs_candidates
  
  #--------------------------------------------- METHODS
  def status=(value)
    write_attribute :status, value.to_s.gsub(/\D/, '').to_i
  end

  def add_pipelines_to_jobs_candidates
    self.job.pipeline_steps.map do |pipeline_step|
      JobsCandidatesPipeline.create({
        jobs_candidate_id: self.id,
        pipeline_step_id: pipeline_step.id 
      })
    end
  end
end

app/controllers/admin/api/v1/jobs_candidates_controller.rb
module Api
  module V1
    class Admin::Api::V1::JobsCandidatesController < ApiController
      before_action :set_jobs_candidate, only: %i[show edit update destroy]

      # GET api/v1/jobs_candidates
      def index
        @presenter = JobsCandidatesPresenter.new(params)
        json_response(data: ActiveModel::Serializer::CollectionSerializer.new(@presenter.jobs_candidates, serializer: JobsCandidateSerializer))
      end

      # GET api/v1/jobs_candidates/1
      def show
        @jobs_candidate = @jobs_candidate.decorate
        json_response(data: JobsCandidateSerializer.new(@jobs_candidate))
      end

      # POST api/v1/jobs_candidates
      def create
        jobs_candidate_manager = JobsCandidateManager.new(params: params)

        if jobs_candidate_manager.create
          jobs_candidate = jobs_candidate_manager.object.decorate
          json_response(message: I18n.t(:success, scope: %i[messages create]), data: JobsCandidateSerializer.new(jobs_candidate), status: :created)
        else
          json_response(message: I18n.t(:error, scope: %i[messages create]), data: JobsCandidateSerializer.object.errors, status: :unprocessable_entity)
        end
      end

      # PATCH/PUT api/v1/jobs_candidates/1
      def update
        jobs_candidate_manager = JobsCandidateManager.new(params: params, object: @jobs_candidate)

        if jobs_candidate_manager.update
          json_response(message: I18n.t(:success, scope: %i[messages update]), status: :ok)
        else
          json_response(message: I18n.t(:error, scope: %i[messages update]), data: jobs_candidate_manager.object.errors, status: :unprocessable_entity)
        end
      end

      # DELETE api/v1/jobs_candidates/1
      def destroy
        jobs_candidate_manager = JobsCandidateManager.new(object: @jobs_candidate)

        if jobs_candidate_manager.destroy
          json_response(message: I18n.t(:success, scope: %i[messages destroy]), status: :ok)
        else
          json_response(message: I18n.t(:error, scope: %i[messages destroy]), status: :unprocessable_entity)
        end
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_jobs_candidate
        @jobs_candidate = jobs_candidate.find(params[:id])
      end
    end
  end
end

app/controllers/admin/jobs_candidates_controller.rb
module Admin 
  class JobsCandidatesController < ApplicationController
    before_action :set_jobs_candidate, only: %i[ show edit update destroy ]

    # GET /jobs_candidates
    def index
      @presenter = JobsCandidatesPresenter.new(params)
    end

    # GET /jobs_candidates/1
    def show
      @jobs_candidate = @jobs_candidate.decorate
    end

    # GET /jobs_candidates/new
    def new
      jobs_candidate_manager = JobsCandidateManager.new(params: params)
      @jobs_candidate = jobs_candidate_manager.build
    end

    # GET /jobs_candidates/1/edit
    def edit
    end

    # POST /jobs_candidates
    def create
      jobs_candidate_manager = JobsCandidateManager.new(params: params)

      if jobs_candidate_manager.create
        redirect_to admin_jobs_candidates_url, notice: "Job Candidate was successfully created."
      else
        @jobs_candidate = jobs_candidate_manager.object
        flash.now[:error] = "Job Candidate could not create."
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /jobs_candidates/1
    def update
      jobs_candidate_manager = JobsCandidateManager.new(params: params, object: @jobs_candidate)

      if jobs_candidate_manager.update
        redirect_to admin_jobs_candidates_url, notice: "Job Candidate was successfully updated."
      else
        @jobs_candidate = jobs_candidate_manager.object
        flash.now[:error] = "Job Candidate could not update."
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /jobs_candidates/1
    def destroy
      jobs_candidate_manager = JobsCandidateManager.new(object: @jobs_candidate)

      if jobs_candidate_manager.destroy
        flash[:notice] = "Job Candidate was successfully destroyed."
        redirect_to admin_jobs_candidates_url
      else
        flash[:error] = "Job Candidate could not destroy."
        redirect_to admin_jobs_candidates_url
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_jobs_candidate
        @jobs_candidate = JobsCandidate.find(params[:id])
      end
  end
end

app/helpers/jobs_candidates_helper.rb
module JobsCandidatesHelper
end

app/views/admin/jobs_candidates/_form.html.erb
<%= form_with(model: @jobs_candidate, url: @jobs_candidate.new_record? ? admin_jobs_candidates_path : admin_jobs_candidate_path(@jobs_candidate)) do |form| %>
  <% if @jobs_candidate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@jobs_candidate.errors.count, "error") %> prohibited this jobs_candidate from being saved:</h2>

      <ul>
        <% @jobs_candidate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :job_id, style: "display: block" %>
    <%= form.text_field :job_id %>
  </div>

  <div>
    <%= form.label :candidate_id, style: "display: block" %>
    <%= form.text_field :candidate_id %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.label :notifications, style: "display: block" %>
    <%= form.check_box :notifications %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/jobs_candidates/_jobs_candidate.html.erb
<div id="<%= dom_id jobs_candidate %>">
  <p>
    <strong>Job:</strong>
    <%= jobs_candidate.job_id %>
  </p>

  <p>
    <strong>Candidate:</strong>
    <%= jobs_candidate.candidate_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= jobs_candidate.status %>
  </p>

  <p>
    <strong>Notifications:</strong>
    <%= jobs_candidate.notifications %>
  </p>

</div>

app/views/admin/jobs_candidates/edit.html.erb
<h1>Editing jobs candidate</h1>

<%= render "form" %>

<br>

<div>
  <%= link_to "Show this jobs candidate", admin_jobs_candidate_path(@jobs_candidate) %> |
  <%= link_to "Back to jobs candidates", admin_jobs_candidates_path %>
</div>

app/views/admin/jobs_candidates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Jobs candidates</h1>

<div id="jobs_candidates">
  <% @presenter.jobs_candidates.each do |jobs_candidate| %>
    <%= render jobs_candidate %>
    <p>
      <%= link_to "Show this jobs candidate", admin_jobs_candidate_path(jobs_candidate) %>
    </p>
  <% end %>
</div>

<%= link_to "New jobs candidate", new_admin_jobs_candidate_path %>

app/views/admin/jobs_candidates/new.html.erb
<h1>New jobs candidate</h1>

<%= render "form" %>

<br>

<div>
  <%= link_to "Back to jobs candidates", admin_jobs_candidates_path %>
</div>

app/views/admin/jobs_candidates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @jobs_candidate %>

<div>
  <%= link_to "Edit this jobs candidate", edit_admin_jobs_candidate_path(@jobs_candidate) %> |
  <%= link_to "Back to jobs candidates", admin_jobs_candidates_path %>

  <%= button_to "Destroy this jobs candidate", admin_jobs_candidate_path(@jobs_candidate), method: :delete %>
</div>