config/routes.rb
Rails.application.routes.draw do
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

namespace :admin do
    namespace :api, defaults: {format: :json} do
      namespace :v1 do
        resources :recruiters
        resources :jobs
        resources :pipeline_steps
        resources :candidates
        resources :jobs_candidates
        resources :jobs_candidates_pipelines, only: [:update]
      end
    end

    resources :recruiters
    resources :jobs
    resources :pipeline_steps
    resources :candidates
    resources :jobs_candidates
    resources :jobs_candidates_pipelines, only: [:update]
end

# Defines the root path route ("/")
# root "articles#index"
get 'postulation/:token', to: 'candidates_experiences#index'

end

app/models/candidate.rb
class Candidate < ApplicationRecord
  #--------------------------------------------- RELATIONSHIPS

  #--------------------------------------------- VALIDATIONS
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :contact_email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
end

app/controllers/admin/api/v1/candidates_controller.rb
module Api
  module V1
    class Admin::Api::V1::CandidatesController < ApiController
      before_action :set_candidate, only: %i[show edit update destroy]

      # GET api/v1/candidates
      def index
        @presenter = CandidatesPresenter.new(params)
        json_response(data: ActiveModel::Serializer::CollectionSerializer.new(@presenter.candidates, serializer: CandidateSerializer))
      end

      # GET api/v1/candidates/1
      def show
        @candidate = @candidate.decorate
        json_response(data: CandidateSerializer.new(@candidate))
      end

      # POST api/v1/candidates
      def create
        candidate_manager = CandidateManager.new(params: params)

        if candidate_manager.create
          candidate = candidate_manager.object.decorate
          json_response(message: I18n.t(:success, scope: %i[messages create]), data: CandidateSerializer.new(candidate), status: :created)
        else
          json_response(message: I18n.t(:error, scope: %i[messages create]), data: candidate_manager.object.errors, status: :unprocessable_entity)
        end
      end

      # PATCH/PUT api/v1/candidates/1
      def update
        candidate_manager = CandidateManager.new(params: params, object: @candidate)

        if candidate_manager.update
          json_response(message: I18n.t(:success, scope: %i[messages update]), status: :ok)
        else
          json_response(message: I18n.t(:error, scope: %i[messages update]), data: candidate_manager.object.errors, status: :unprocessable_entity)
        end
      end

      # DELETE api/v1/candidates/1
      def destroy
        candidate_manager = CandidateManager.new(object: @candidate)

        if candidate_manager.destroy
          json_response(message: I18n.t(:success, scope: %i[messages destroy]), status: :ok)
        else
          json_response(message: I18n.t(:error, scope: %i[messages destroy]), status: :unprocessable_entity)
        end
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_candidate
        @candidate = Candidate.find(params[:id])
      end
    end
  end
end

app/controllers/admin/candidates_controller.rb
module Admin 
  class CandidatesController < ApplicationController
    before_action :set_candidate, only: %i[ show edit update destroy ]

    # GET /candidates
    def index
      @presenter = CandidatesPresenter.new(params)
    end

    # GET /candidates/1
    def show
      @candidate = @candidate.decorate
    end

    # GET /candidates/new
    def new
      candidate_manager = CandidateManager.new(params: params)
      @candidate = candidate_manager.build
    end

    # GET /candidates/1/edit
    def edit
    end

    # POST /candidates
    def create
      candidate_manager = CandidateManager.new(params: params)

      if candidate_manager.create
        redirect_to admin_candidates_url, notice: "Candidate was successfully created."
      else
        @candidate = candidate_manager.object
        flash.now[:error] = "Candidate could not create."
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /candidates/1
    def update
      candidate_manager = CandidateManager.new(params: params, object: @candidate)

      if candidate_manager.update
        redirect_to admin_candidates_url, notice: "Candidates was successfully updated."
      else
        @candidate = candidate_manager.object
        flash.now[:error] = "Candidates could not update."
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /candidates/1
    def destroy
      candidate_manager = CandidateManager.new(object: @candidate)

      if candidate_manager.destroy
        flash[:notice] = "Candidates was successfully destroyed."
        redirect_to admin_candidates_url
      else
        flash[:error] = "Candidates could not destroy."
        redirect_to admin_candidates_url
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_candidate
        @candidate = Candidate.find(params[:id])
      end
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/admin/candidates/_candidate.html.erb
<div id="<%= dom_id candidate %>">
  <p>
    <strong>First name:</strong>
    <%= candidate.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= candidate.last_name %>
  </p>

  <p>
    <strong>Contact email:</strong>
    <%= candidate.contact_email %>
  </p>

  <p>
    <strong>Contact linked in:</strong>
    <%= candidate.contact_linked_in %>
  </p>

</div>

app/views/admin/candidates/_form.html.erb
<%= form_with(model: @candidate, url: @candidate.new_record? ? admin_candidates_path : admin_candidate_path(@candidate)) do |form| %>
  <% if @candidate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
        <% @candidate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :contact_email, style: "display: block" %>
    <%= form.text_field :contact_email %>
  </div>

  <div>
    <%= form.label :contact_linked_in, style: "display: block" %>
    <%= form.text_field :contact_linked_in %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/candidates/edit.html.erb
<h1>Editing candidate</h1>

<%= render "form", candidate: @candidate %>

<br>

<div>
  <%= link_to "Show this candidate", admin_job_path(@candidate) %> |
  <%= link_to "Back to candidates", admin_candidates_path %>
</div>

app/views/admin/candidates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Candidates</h1>

<div id="candidates">
  <% @presenter.candidates.each do |candidate| %>
    <%= render candidate %>
    <p>
      <%= link_to "Show this candidate", admin_candidate_path(candidate) %>
    </p>
  <% end %>
</div>

<%= link_to "New candidate", new_admin_candidate_path %>

app/views/admin/candidates/new.html.erb
<h1>New candidate</h1>

<%= render "form" %>

<br>

<div>
  <%= link_to "Back to candidates", admin_candidates_path %>
</div>

app/views/admin/candidates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @candidate %>

<div>
  <%= link_to "Edit this candidate", edit_admin_candidate_path(@candidate) %> |
  <%= link_to "Back to candidates", admin_candidates_path %>

  <%= button_to "Destroy this candidate", admin_candidate_path(@candidate), method: :delete %>
</div>