config/routes.rb
Rails.application.routes.draw do
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

namespace :admin do
    namespace :api, defaults: {format: :json} do
      namespace :v1 do
        resources :recruiters
        resources :jobs
        resources :pipeline_steps
        resources :candidates
        resources :jobs_candidates
        resources :jobs_candidates_pipelines, only: [:update]
      end
    end

    resources :recruiters
    resources :jobs
    resources :pipeline_steps
    resources :candidates
    resources :jobs_candidates
    resources :jobs_candidates_pipelines, only: [:update]
end

# Defines the root path route ("/")
# root "articles#index"
get 'postulation/:token', to: 'candidates_experiences#index'

end

app/models/recruiter.rb
class Recruiter < ApplicationRecord
    #--------------------------------------------- RELATIONSHIPS

    #--------------------------------------------- VALIDATIONS
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :contact_email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
    validates :role, presence: true
    validates :company_name, presence: true
end

app/controllers/admin/api/v1/recruiters_controller.rb
module Api
  module V1
    class Admin::Api::V1::RecruitersController < ApiController
      before_action :recruiter, only: %i[show edit update destroy]

      # GET api/v1/recruiters
      def index
        @presenter = RecruitersPresenter.new(params)
        json_response(data: ActiveModel::Serializer::CollectionSerializer.new(@presenter.recruiters, serializer: RecruiterSerializer))
      end

      # GET api/v1/recruiters/1
      def show
        @recruiter = @recruiter.decorate
        json_response(data: RecruiterSerializer.new(@recruiter))
      end

      # POST api/v1/recruiters
      def create
        recruiter_manager = RecruiterManager.new(params: params)

        if recruiter_manager.create
          recruiter = recruiter_manager.object.decorate
          json_response(message: I18n.t(:success, scope: %i[messages create]), data: RecruiterSerializer.new(recruiter), status: :created)
        else
          json_response(message: I18n.t(:error, scope: %i[messages create]), data: recruiter_manager.object.errors, status: :unprocessable_entity)
        end
      end

      # PATCH/PUT api/v1/recruiters/1
      def update
        recruiter_manager = RecruiterManager.new(params: params, object: @recruiter)

        if recruiter_manager.update
          json_response(message: I18n.t(:success, scope: %i[messages update]), status: :ok)
        else
          json_response(message: I18n.t(:error, scope: %i[messages update]), data: recruiter_manager.object.errors, status: :unprocessable_entity)
        end
      end

      # DELETE api/v1/recruiters/1
      def destroy
        recruiter_manager = RecruiterManager.new(object: @recruiter)

        if recruiter_manager.destroy
          json_response(message: I18n.t(:success, scope: %i[messages destroy]), status: :ok)
        else
          json_response(message: I18n.t(:error, scope: %i[messages destroy]), status: :unprocessable_entity)
        end
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def recruiter
        @recruiter = Recruiter.find(params[:id])
      end
    end
  end
end

app/controllers/admin/recruiters_controller.rb
module Admin
  class RecruitersController < ApplicationController
    before_action :set_recruiter, only: %i[ show edit update destroy ]

    # GET /recruiters
    def index
      @presenter = RecruitersPresenter.new(params)
    end

    # GET /recruiters/1
    def show
      @recruiter = @recruiter.decorate
    end

    # GET /recruiters/new
    def new
      recruiter_manager = RecruiterManager.new(params: params)
      @recruiter = recruiter_manager.build
    end

    # GET /recruiters/1/edit
    def edit
    end

    # POST /recruiters
    def create
      recruiter_manager = RecruiterManager.new(params: params)

      if recruiter_manager.create
        redirect_to admin_recruiters_url, notice: "Recruiter was successfully created."
      else
        @recruiter = recruiter_manager.object
        flash.now[:error] = "Recruiter could not create."
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /recruiters/1
    def update
      recruiter_manager = RecruiterManager.new(params: params, object: @recruiter)

      if recruiter_manager.update
        redirect_to admin_recruiters_url, notice: "Recruiter was successfully updated."
      else
        @recruiter = recruiter_manager.object
        flash.now[:error] = "Recruiter could not update."
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /recruiters/1
    def destroy
      recruiter_manager = RecruiterManager.new(object: @recruiter)

      if recruiter_manager.destroy
        flash[:notice] = "Recruiter was successfully destroyed."
        redirect_to admin_recruiters_url
      else
        flash[:error] = "Recruiter could not destroy."
        redirect_to admin_recruiters_url
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_recruiter
        @recruiter = Recruiter.find(params[:id])
      end
  end
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/views/admin/recruiters/_form.html.erb
<%= form_with(model: @recruiter, url: @recruiter.new_record? ? admin_recruiters_path : admin_recruiter_path(@recruiter)) do |form| %>
  <% if @recruiter.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@recruiter.errors.count, "error") %> prohibited this @recruiter from being saved:</h2>

      <ul>
        <% @recruiter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :profile_picture_url, style: "display: block" %>
    <%= form.text_field :profile_picture_url %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.check_box :status %>
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.text_field :role %>
  </div>

  <div>
    <%= form.label :company_name, style: "display: block" %>
    <%= form.text_field :company_name %>
  </div>

  <div>
    <%= form.label :contact_email, style: "display: block" %>
    <%= form.text_field :contact_email %>
  </div>

  <div>
    <%= form.label :contact_whatsapp, style: "display: block" %>
    <%= form.text_field :contact_whatsapp %>
  </div>

  <div>
    <%= form.label :contact_linked_in, style: "display: block" %>
    <%= form.text_field :contact_linked_in %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/recruiters/_recruiter.html.erb
<div id="<%= dom_id recruiter %>">
  <p>
    <strong>First name:</strong>
    <%= recruiter.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= recruiter.last_name %>
  </p>

  <p>
    <strong>Profile picture url:</strong>
    <%= recruiter.profile_picture_url %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= recruiter.status %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= recruiter.role %>
  </p>

  <p>
    <strong>Company name:</strong>
    <%= recruiter.company_name %>
  </p>

  <p>
    <strong>Contact email:</strong>
    <%= recruiter.contact_email %>
  </p>

  <p>
    <strong>Contact whatsapp:</strong>
    <%= recruiter.contact_whatsapp %>
  </p>

  <p>
    <strong>Contact linked in:</strong>
    <%= recruiter.contact_linked_in %>
  </p>

</div>

app/views/admin/recruiters/edit.html.erb
<h1>Editing recruiter</h1>

<%= render "form" %>

<br>

<div>
  <%= link_to "Show this recruiter", admin_recruiter_path(@recruiter) %> |
  <%= link_to "Back to recruiters", admin_recruiters_path %>
</div>

app/views/admin/recruiters/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recruiters</h1>

<div id="recruiters">
  <% @presenter.recruiters.each do |recruiter| %>
    <%= render recruiter %>
    <p>
      <%= link_to "Show this recruiter", admin_recruiter_path(recruiter) %>
    </p>
  <% end %>
</div>

<%= link_to "New recruiter", new_admin_recruiter_path %>

app/views/admin/recruiters/new.html.erb
<h1>New recruiter</h1>

<%= render "form" %>

<br>

<div>
  <%= link_to "Back to recruiters", admin_recruiters_path %>
</div>

app/views/admin/recruiters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recruiter %>

<div>
  <%= link_to "Edit this recruiter", edit_admin_recruiter_path(@recruiter) %> |
  <%= link_to "Back to recruiters", admin_recruiters_path %>

  <%= button_to "Destroy this recruiter",admin_recruiter_path(@recruiter), method: :delete %>
</div>