config/routes.rb
Rails.application.routes.draw do
# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

namespace :admin do
    namespace :api, defaults: {format: :json} do
      namespace :v1 do
        resources :recruiters
        resources :jobs
        resources :pipeline_steps
        resources :candidates
        resources :jobs_candidates
        resources :jobs_candidates_pipelines, only: [:update]
      end
    end

    resources :recruiters
    resources :jobs
    resources :pipeline_steps
    resources :candidates
    resources :jobs_candidates
    resources :jobs_candidates_pipelines, only: [:update]
end

# Defines the root path route ("/")
# root "articles#index"
get 'postulation/:token', to: 'candidates_experiences#index'

end

app/models/job.rb
class Job < ApplicationRecord
  #--------------------------------------------- RELATIONSHIPS
  belongs_to :recruiter
  has_many :pipeline_steps
  has_many :jobs_candidates
  #--------------------------------------------- VALIDATIONS
  validates :title, presence: true, length: { minimum: 10 }
  validates :description, presence: true, length: { minimum: 100 }
  validates :ats_link, presence: true
end

app/controllers/admin/api/v1/jobs_controller.rb
module Api
  module V1
    class Admin::Api::V1::JobsController < ApiController
      before_action :set_job, only: %i[show edit update destroy]

      # GET api/v1/jobs
      def index
        @presenter = JobsPresenter.new(params)
        json_response(data: ActiveModel::Serializer::CollectionSerializer.new(@presenter.jobs, serializer: JobSerializer))
      end

      # GET api/v1/jobs/1
      def show
        @job = @job.decorate
        json_response(data: JobSerializer.new(@job))
      end

      # POST api/v1/jobs
      def create
        job_manager = JobManager.new(params: params)

        if job_manager.create
          job = job_manager.object.decorate
          json_response(message: I18n.t(:success, scope: %i[messages create]), data: JobSerializer.new(job), status: :created)
        else
          json_response(message: I18n.t(:error, scope: %i[messages create]), data: job_manager.object.errors, status: :unprocessable_entity)
        end
      end

      # PATCH/PUT api/v1/jobs/1
      def update
        job_manager = JobManager.new(params: params, object: @job)

        if job_manager.update
          json_response(message: I18n.t(:success, scope: %i[messages update]), status: :ok)
        else
          json_response(message: I18n.t(:error, scope: %i[messages update]), data: job_manager.object.errors, status: :unprocessable_entity)
        end
      end

      # DELETE api/v1/jobs/1
      def destroy
        job_manager = JobManager.new(object: @job)

        if job_manager.destroy
          json_response(message: I18n.t(:success, scope: %i[messages destroy]), status: :ok)
        else
          json_response(message: I18n.t(:error, scope: %i[messages destroy]), status: :unprocessable_entity)
        end
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_job
        @job = Job.find(params[:id])
      end
    end
  end
end

app/controllers/admin/jobs_controller.rb
module Admin 
  class JobsController < ApplicationController
    before_action :set_job, only: %i[ show edit update destroy ]

    # GET /jobs
    def index
      @presenter = JobsPresenter.new(params)
    end

    # GET /jobs/1
    def show
      @job = @job.decorate
    end

    # GET /jobs/new
    def new
      job_manager = JobManager.new(params: params)
      @job = job_manager.build
    end

    # GET /jobs/1/edit
    def edit
    end

    # POST /jobs
    def create
      job_manager = JobManager.new(params: params)

      if job_manager.create
        redirect_to admin_jobs_url, notice: "Job was successfully created."
      else
        @job = job_manager.object
        flash.now[:error] = "Job could not create."
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /jobs/1
    def update
      job_manager = JobManager.new(params: params, object: @job)

      if job_manager.update
        redirect_to admin_jobs_url, notice: "Job was successfully updated."
      else
        @job = job_manager.object
        flash.now[:error] = "Job could not update."
        render :edit, status: :unprocessable_entity
      end
    end

    # DELETE /jobs/1
    def destroy
      job_manager = JobManager.new(object: @job)

      if job_manager.destroy
        flash[:notice] = "Job was successfully destroyed."
        redirect_to admin_jobs_url
      else
        flash[:error] = "Job could not destroy."
        redirect_to admin_jobs_url
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_job
        @job = Job.find(params[:id])
      end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/admin/jobs/_form.html.erb
<%= form_with(model: @job, url: @job.new_record? ? admin_jobs_path : admin_job_path(@job)) do |form| %>
  <% if @job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this @job from being saved:</h2>

      <ul>
        <% @job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>

  <div>
    <%= form.label :ats_link, style: "display: block" %>
    <%= form.text_field :ats_link %>
  </div>

  <div>
    <%= form.label :recruiter_id, style: "display: block" %>
    <%= form.text_field :recruiter_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/jobs/_job.html.erb
<div id="<%= dom_id job %>">
  <p>
    <strong>Title:</strong>
    <%= job.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= job.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= job.status %>
  </p>

  <p>
    <strong>Ats link:</strong>
    <%= job.ats_link %>
  </p>

  <p>
    <strong>Recruiter:</strong>
    <%= job.recruiter_id %>
  </p>

</div>

app/views/admin/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form" %>

<br>

<div>
  <%= link_to "Show this job", admin_job_path(@job) %> |
  <%= link_to "Back to jobs", admin_jobs_path %>
</div>

app/views/admin/jobs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Jobs</h1>

<div id="jobs">
  <% @presenter.jobs.each do |job| %>
    <%= render job %>
    <p>
      <%= link_to "Show this job", admin_job_path(job) %>
    </p>
  <% end %>
</div>

<%= link_to "New job", new_admin_job_path, :class => 'btn btn-primary text-white' %>

app/views/admin/jobs/new.html.erb
<h1>New job</h1>

<%= render "form" %>

<br>

<div>
  <%= link_to "Back to jobs", admin_jobs_path %>
</div>

app/views/admin/jobs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job %>

<div>
  <%= link_to "Edit this job", edit_admin_job_path(@job) %> |
  <%= link_to "Back to jobs", admin_jobs_path %>

  <%= button_to "Destroy this job", admin_job_path(@job), method: :delete %>
</div>